// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - TanStack devtools (dev-only, first), tanstackStart, viteReact, tailwindcss, tsConfigPaths,
//     nitro (build-only using cloudflare as a default target), VITE_* env injection, @ path alias,
//     React/TanStack dedupe, error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import { VitePWA } from "vite-plugin-pwa";
import type { PluginOption } from "vite";

/** Restricts a plugin (or plugin array) to Vite's client environment. */
function clientOnly(plugins: PluginOption): PluginOption {
  const list = Array.isArray(plugins) ? plugins : [plugins];
  return list.map((plugin) =>
    plugin && typeof plugin === "object" && !Array.isArray(plugin) && !("then" in plugin)
      ? { ...plugin, applyToEnvironment: (env: { name: string }) => env.name === "client" }
      : plugin,
  ) as PluginOption;
}

export default defineConfig({
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
  nitro: {
    preset: process.env.VERCEL ? "vercel" : process.env.NETLIFY ? "netlify" : undefined,
  },
  plugins: [
    // Generate the worker once, from the browser build only.
    clientOnly(
      VitePWA({
        // The service worker is generated by Workbox; never hand-written.
        strategies: "generateSW",
        registerType: "autoUpdate",
        // Registration lives in src/lib/pwa.ts behind preview/dev guards.
        injectRegister: null,
        // Never emit or register a service worker in dev / Lovable preview.
        devOptions: { enabled: false },
        filename: "sw.js",
        // Nitro serves the browser build from dist/client — the worker must live there.
        outDir: "dist/client",
        // The manifest is authored by hand in public/manifest.webmanifest.
        manifest: false,
        includeAssets: [],
        workbox: {
          globPatterns: ["**/*.{js,css,woff,woff2,png,svg,ico,webmanifest}"],
          globIgnores: ["**/_server/**", "**/node_modules/**"],
          cleanupOutdatedCaches: true,
          clientsClaim: true,
          skipWaiting: true,
          // This app is server-rendered: HTML must always come from the network first.
          navigateFallback: undefined,
          maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
          runtimeCaching: [
            {
              // Pages: fresh when online, last-seen copy when offline.
              urlPattern: ({ request }: { request: Request }) => request.mode === "navigate",
              handler: "NetworkFirst",
              options: {
                cacheName: "canteenos-pages",
                networkTimeoutSeconds: 4,
                expiration: { maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 7 },
                cacheableResponse: { statuses: [0, 200] },
              },
            },
            {
              urlPattern: ({ request, url }: { request: Request; url: URL }) =>
                url.origin === self.location.origin &&
                ["script", "style", "worker"].includes(request.destination),
              handler: "StaleWhileRevalidate",
              options: { cacheName: "canteenos-assets" },
            },
            {
              urlPattern: ({ request }: { request: Request }) => request.destination === "image",
              handler: "CacheFirst",
              options: {
                cacheName: "canteenos-images",
                expiration: { maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 },
                cacheableResponse: { statuses: [0, 200] },
              },
            },
            {
              urlPattern: ({ url }: { url: URL }) => url.origin === "https://fonts.gstatic.com",
              handler: "CacheFirst",
              options: {
                cacheName: "canteenos-fonts",
                expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
                cacheableResponse: { statuses: [0, 200] },
              },
            },
          ],
          // OAuth and API traffic must never be served from a cache.
          navigateFallbackDenylist: [/^\/~oauth/, /^\/api\//],
        },
      }),
    ),
  ],
});
