// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      const isLocalhost =
        typeof window !== "undefined" &&
        (window.location.hostname === "localhost" ||
          window.location.hostname === "127.0.0.1" ||
          window.location.hostname.endsWith(".localhost"));

      if (isLocalhost) {
        if (provider === "lovable") {
          return { error: new Error("Lovable OAuth is only available in Lovable Cloud environment.") };
        }
        const { data, error } = await supabase.auth.signInWithOAuth({
          provider: provider as "google" | "apple" | "azure",
          options: {
            redirectTo: opts?.redirect_uri || `${window.location.origin}/app`,
          },
        });
        if (error) return { error };
        if (data?.url) {
          window.location.href = data.url;
          return { redirected: true, error: null };
        }
        return { error: null, redirected: false };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
