/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CheckoutPlanRouteImport } from './routes/checkout-plan'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminNotificationLabRouteImport } from './routes/admin.notification-lab'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWorkforceRouteImport } from './routes/admin.workforce'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as KitchenIndexRouteImport } from './routes/kitchen.index'
import { Route as KitchenHistoryRouteImport } from './routes/kitchen.history'
import { Route as KitchenMenuRouteImport } from './routes/kitchen.menu'
import { Route as KitchenNotificationsRouteImport } from './routes/kitchen.notifications'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin.analytics.index'
import { Route as AdminAnalyticsCustomersRouteImport } from './routes/admin.analytics.customers'
import { Route as AdminAnalyticsInventoryRouteImport } from './routes/admin.analytics.inventory'
import { Route as AdminAnalyticsOrdersRouteImport } from './routes/admin.analytics.orders'
import { Route as AdminAnalyticsRevenueRouteImport } from './routes/admin.analytics.revenue'
import { Route as AdminAnalyticsSalesRouteImport } from './routes/admin.analytics.sales'
import { Route as AdminAnalyticsStaffRouteImport } from './routes/admin.analytics.staff'
import { Route as AdminMonitoringIndexRouteImport } from './routes/admin.monitoring.index'
import { Route as AdminMonitoringActivityRouteImport } from './routes/admin.monitoring.activity'
import { Route as AdminMonitoringApiRouteImport } from './routes/admin.monitoring.api'
import { Route as AdminMonitoringDatabaseRouteImport } from './routes/admin.monitoring.database'
import { Route as AdminMonitoringErrorsRouteImport } from './routes/admin.monitoring.errors'
import { Route as AdminMonitoringIntegrationsRouteImport } from './routes/admin.monitoring.integrations'
import { Route as AdminMonitoringLiveRouteImport } from './routes/admin.monitoring.live'
import { Route as AdminMonitoringPerformanceRouteImport } from './routes/admin.monitoring.performance'
import { Route as AdminOrganizationIndexRouteImport } from './routes/admin.organization.index'
import { Route as AdminOrganizationAnalyticsRouteImport } from './routes/admin.organization.analytics'
import { Route as AdminOrganizationCampusesRouteImport } from './routes/admin.organization.campuses'
import { Route as AdminOrganizationCanteensRouteImport } from './routes/admin.organization.canteens'
import { Route as AdminOrganizationSettingsRouteImport } from './routes/admin.organization.settings'
import { Route as AdminWorkforceIndexRouteImport } from './routes/admin.workforce.index'
import { Route as AdminWorkforceAttendanceRouteImport } from './routes/admin.workforce.attendance'
import { Route as AdminWorkforceShiftsRouteImport } from './routes/admin.workforce.shifts'
import { Route as AppMenuIndexRouteImport } from './routes/app.menu.index'
import { Route as AppMenuItemIdRouteImport } from './routes/app.menu.$itemId'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/app.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanRoute = CheckoutPlanRouteImport.update({
  id: '/checkout-plan',
  path: '/checkout-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationLabRoute = AdminNotificationLabRouteImport.update({
  id: '/notification-lab',
  path: '/notification-lab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenHistoryRoute = KitchenHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenMenuRoute = KitchenMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenNotificationsRoute = KitchenNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => KitchenRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsCustomersRoute = AdminAnalyticsCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsInventoryRoute = AdminAnalyticsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsOrdersRoute = AdminAnalyticsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsRevenueRoute = AdminAnalyticsRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsSalesRoute = AdminAnalyticsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsStaffRoute = AdminAnalyticsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminMonitoringIndexRoute = AdminMonitoringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMonitoringRoute,
} as any)
const AdminMonitoringActivityRoute = AdminMonitoringActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminMonitoringRoute,
} as any)
const AdminMonitoringApiRoute = AdminMonitoringApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminMonitoringRoute,
} as any)
const AdminMonitoringDatabaseRoute = AdminMonitoringDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminMonitoringRoute,
} as any)
const AdminMonitoringErrorsRoute = AdminMonitoringErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminMonitoringRoute,
} as any)
const AdminMonitoringIntegrationsRoute =
  AdminMonitoringIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AdminMonitoringRoute,
  } as any)
const AdminMonitoringLiveRoute = AdminMonitoringLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminMonitoringRoute,
} as any)
const AdminMonitoringPerformanceRoute =
  AdminMonitoringPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AdminMonitoringRoute,
  } as any)
const AdminOrganizationIndexRoute = AdminOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrganizationRoute,
} as any)
const AdminOrganizationAnalyticsRoute =
  AdminOrganizationAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminOrganizationRoute,
  } as any)
const AdminOrganizationCampusesRoute =
  AdminOrganizationCampusesRouteImport.update({
    id: '/campuses',
    path: '/campuses',
    getParentRoute: () => AdminOrganizationRoute,
  } as any)
const AdminOrganizationCanteensRoute =
  AdminOrganizationCanteensRouteImport.update({
    id: '/canteens',
    path: '/canteens',
    getParentRoute: () => AdminOrganizationRoute,
  } as any)
const AdminOrganizationSettingsRoute =
  AdminOrganizationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminOrganizationRoute,
  } as any)
const AdminWorkforceIndexRoute = AdminWorkforceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWorkforceRoute,
} as any)
const AdminWorkforceAttendanceRoute =
  AdminWorkforceAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AdminWorkforceRoute,
  } as any)
const AdminWorkforceShiftsRoute = AdminWorkforceShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminWorkforceRoute,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuItemIdRoute = AppMenuItemIdRouteImport.update({
  id: '/menu/$itemId',
  path: '/menu/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/checkout-plan': typeof CheckoutPlanRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen': typeof KitchenRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-error': typeof ServerErrorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/monitoring': typeof AdminMonitoringRouteWithChildren
  '/admin/notification-lab': typeof AdminNotificationLabRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/organization': typeof AdminOrganizationRouteWithChildren
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workforce': typeof AdminWorkforceRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/kitchen/history': typeof KitchenHistoryRoute
  '/kitchen/menu': typeof KitchenMenuRoute
  '/kitchen/notifications': typeof KitchenNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/admin/analytics/customers': typeof AdminAnalyticsCustomersRoute
  '/admin/analytics/inventory': typeof AdminAnalyticsInventoryRoute
  '/admin/analytics/orders': typeof AdminAnalyticsOrdersRoute
  '/admin/analytics/revenue': typeof AdminAnalyticsRevenueRoute
  '/admin/analytics/sales': typeof AdminAnalyticsSalesRoute
  '/admin/analytics/staff': typeof AdminAnalyticsStaffRoute
  '/admin/monitoring/activity': typeof AdminMonitoringActivityRoute
  '/admin/monitoring/api': typeof AdminMonitoringApiRoute
  '/admin/monitoring/database': typeof AdminMonitoringDatabaseRoute
  '/admin/monitoring/errors': typeof AdminMonitoringErrorsRoute
  '/admin/monitoring/integrations': typeof AdminMonitoringIntegrationsRoute
  '/admin/monitoring/live': typeof AdminMonitoringLiveRoute
  '/admin/monitoring/performance': typeof AdminMonitoringPerformanceRoute
  '/admin/organization/analytics': typeof AdminOrganizationAnalyticsRoute
  '/admin/organization/campuses': typeof AdminOrganizationCampusesRoute
  '/admin/organization/canteens': typeof AdminOrganizationCanteensRoute
  '/admin/organization/settings': typeof AdminOrganizationSettingsRoute
  '/admin/workforce/attendance': typeof AdminWorkforceAttendanceRoute
  '/admin/workforce/shifts': typeof AdminWorkforceShiftsRoute
  '/app/menu/$itemId': typeof AppMenuItemIdRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/monitoring/': typeof AdminMonitoringIndexRoute
  '/admin/organization/': typeof AdminOrganizationIndexRoute
  '/admin/workforce/': typeof AdminWorkforceIndexRoute
  '/app/menu/': typeof AppMenuIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout-plan': typeof CheckoutPlanRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-error': typeof ServerErrorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notification-lab': typeof AdminNotificationLabRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/ai': typeof AppAiRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/kitchen/history': typeof KitchenHistoryRoute
  '/kitchen/menu': typeof KitchenMenuRoute
  '/kitchen/notifications': typeof KitchenNotificationsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/admin/analytics/customers': typeof AdminAnalyticsCustomersRoute
  '/admin/analytics/inventory': typeof AdminAnalyticsInventoryRoute
  '/admin/analytics/orders': typeof AdminAnalyticsOrdersRoute
  '/admin/analytics/revenue': typeof AdminAnalyticsRevenueRoute
  '/admin/analytics/sales': typeof AdminAnalyticsSalesRoute
  '/admin/analytics/staff': typeof AdminAnalyticsStaffRoute
  '/admin/monitoring/activity': typeof AdminMonitoringActivityRoute
  '/admin/monitoring/api': typeof AdminMonitoringApiRoute
  '/admin/monitoring/database': typeof AdminMonitoringDatabaseRoute
  '/admin/monitoring/errors': typeof AdminMonitoringErrorsRoute
  '/admin/monitoring/integrations': typeof AdminMonitoringIntegrationsRoute
  '/admin/monitoring/live': typeof AdminMonitoringLiveRoute
  '/admin/monitoring/performance': typeof AdminMonitoringPerformanceRoute
  '/admin/organization/analytics': typeof AdminOrganizationAnalyticsRoute
  '/admin/organization/campuses': typeof AdminOrganizationCampusesRoute
  '/admin/organization/canteens': typeof AdminOrganizationCanteensRoute
  '/admin/organization/settings': typeof AdminOrganizationSettingsRoute
  '/admin/workforce/attendance': typeof AdminWorkforceAttendanceRoute
  '/admin/workforce/shifts': typeof AdminWorkforceShiftsRoute
  '/app/menu/$itemId': typeof AppMenuItemIdRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/monitoring': typeof AdminMonitoringIndexRoute
  '/admin/organization': typeof AdminOrganizationIndexRoute
  '/admin/workforce': typeof AdminWorkforceIndexRoute
  '/app/menu': typeof AppMenuIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/checkout-plan': typeof CheckoutPlanRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen': typeof KitchenRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-error': typeof ServerErrorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/monitoring': typeof AdminMonitoringRouteWithChildren
  '/admin/notification-lab': typeof AdminNotificationLabRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/organization': typeof AdminOrganizationRouteWithChildren
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workforce': typeof AdminWorkforceRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/kitchen/history': typeof KitchenHistoryRoute
  '/kitchen/menu': typeof KitchenMenuRoute
  '/kitchen/notifications': typeof KitchenNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/admin/analytics/customers': typeof AdminAnalyticsCustomersRoute
  '/admin/analytics/inventory': typeof AdminAnalyticsInventoryRoute
  '/admin/analytics/orders': typeof AdminAnalyticsOrdersRoute
  '/admin/analytics/revenue': typeof AdminAnalyticsRevenueRoute
  '/admin/analytics/sales': typeof AdminAnalyticsSalesRoute
  '/admin/analytics/staff': typeof AdminAnalyticsStaffRoute
  '/admin/monitoring/activity': typeof AdminMonitoringActivityRoute
  '/admin/monitoring/api': typeof AdminMonitoringApiRoute
  '/admin/monitoring/database': typeof AdminMonitoringDatabaseRoute
  '/admin/monitoring/errors': typeof AdminMonitoringErrorsRoute
  '/admin/monitoring/integrations': typeof AdminMonitoringIntegrationsRoute
  '/admin/monitoring/live': typeof AdminMonitoringLiveRoute
  '/admin/monitoring/performance': typeof AdminMonitoringPerformanceRoute
  '/admin/organization/analytics': typeof AdminOrganizationAnalyticsRoute
  '/admin/organization/campuses': typeof AdminOrganizationCampusesRoute
  '/admin/organization/canteens': typeof AdminOrganizationCanteensRoute
  '/admin/organization/settings': typeof AdminOrganizationSettingsRoute
  '/admin/workforce/attendance': typeof AdminWorkforceAttendanceRoute
  '/admin/workforce/shifts': typeof AdminWorkforceShiftsRoute
  '/app/menu/$itemId': typeof AppMenuItemIdRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/monitoring/': typeof AdminMonitoringIndexRoute
  '/admin/organization/': typeof AdminOrganizationIndexRoute
  '/admin/workforce/': typeof AdminWorkforceIndexRoute
  '/app/menu/': typeof AppMenuIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/checkout-plan'
    | '/contact'
    | '/forbidden'
    | '/forgot-password'
    | '/kitchen'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/register'
    | '/reset-password'
    | '/server-error'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/monitoring'
    | '/admin/notification-lab'
    | '/admin/notifications'
    | '/admin/organization'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/admin/workforce'
    | '/app/ai'
    | '/app/cart'
    | '/app/checkout'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/kitchen/history'
    | '/kitchen/menu'
    | '/kitchen/notifications'
    | '/admin/'
    | '/app/'
    | '/kitchen/'
    | '/admin/analytics/customers'
    | '/admin/analytics/inventory'
    | '/admin/analytics/orders'
    | '/admin/analytics/revenue'
    | '/admin/analytics/sales'
    | '/admin/analytics/staff'
    | '/admin/monitoring/activity'
    | '/admin/monitoring/api'
    | '/admin/monitoring/database'
    | '/admin/monitoring/errors'
    | '/admin/monitoring/integrations'
    | '/admin/monitoring/live'
    | '/admin/monitoring/performance'
    | '/admin/organization/analytics'
    | '/admin/organization/campuses'
    | '/admin/organization/canteens'
    | '/admin/organization/settings'
    | '/admin/workforce/attendance'
    | '/admin/workforce/shifts'
    | '/app/menu/$itemId'
    | '/app/orders/$orderId'
    | '/admin/analytics/'
    | '/admin/monitoring/'
    | '/admin/organization/'
    | '/admin/workforce/'
    | '/app/menu/'
    | '/app/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout-plan'
    | '/contact'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/register'
    | '/reset-password'
    | '/server-error'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/notification-lab'
    | '/admin/notifications'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/app/ai'
    | '/app/cart'
    | '/app/checkout'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/kitchen/history'
    | '/kitchen/menu'
    | '/kitchen/notifications'
    | '/admin'
    | '/app'
    | '/kitchen'
    | '/admin/analytics/customers'
    | '/admin/analytics/inventory'
    | '/admin/analytics/orders'
    | '/admin/analytics/revenue'
    | '/admin/analytics/sales'
    | '/admin/analytics/staff'
    | '/admin/monitoring/activity'
    | '/admin/monitoring/api'
    | '/admin/monitoring/database'
    | '/admin/monitoring/errors'
    | '/admin/monitoring/integrations'
    | '/admin/monitoring/live'
    | '/admin/monitoring/performance'
    | '/admin/organization/analytics'
    | '/admin/organization/campuses'
    | '/admin/organization/canteens'
    | '/admin/organization/settings'
    | '/admin/workforce/attendance'
    | '/admin/workforce/shifts'
    | '/app/menu/$itemId'
    | '/app/orders/$orderId'
    | '/admin/analytics'
    | '/admin/monitoring'
    | '/admin/organization'
    | '/admin/workforce'
    | '/app/menu'
    | '/app/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/checkout-plan'
    | '/contact'
    | '/forbidden'
    | '/forgot-password'
    | '/kitchen'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/register'
    | '/reset-password'
    | '/server-error'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/monitoring'
    | '/admin/notification-lab'
    | '/admin/notifications'
    | '/admin/organization'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/admin/workforce'
    | '/app/ai'
    | '/app/cart'
    | '/app/checkout'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/kitchen/history'
    | '/kitchen/menu'
    | '/kitchen/notifications'
    | '/admin/'
    | '/app/'
    | '/kitchen/'
    | '/admin/analytics/customers'
    | '/admin/analytics/inventory'
    | '/admin/analytics/orders'
    | '/admin/analytics/revenue'
    | '/admin/analytics/sales'
    | '/admin/analytics/staff'
    | '/admin/monitoring/activity'
    | '/admin/monitoring/api'
    | '/admin/monitoring/database'
    | '/admin/monitoring/errors'
    | '/admin/monitoring/integrations'
    | '/admin/monitoring/live'
    | '/admin/monitoring/performance'
    | '/admin/organization/analytics'
    | '/admin/organization/campuses'
    | '/admin/organization/canteens'
    | '/admin/organization/settings'
    | '/admin/workforce/attendance'
    | '/admin/workforce/shifts'
    | '/app/menu/$itemId'
    | '/app/orders/$orderId'
    | '/admin/analytics/'
    | '/admin/monitoring/'
    | '/admin/organization/'
    | '/admin/workforce/'
    | '/app/menu/'
    | '/app/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CheckoutPlanRoute: typeof CheckoutPlanRoute
  ContactRoute: typeof ContactRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenRoute: typeof KitchenRouteWithChildren
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfflineRoute: typeof OfflineRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServerErrorRoute: typeof ServerErrorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-plan': {
      id: '/checkout-plan'
      path: '/checkout-plan'
      fullPath: '/checkout-plan'
      preLoaderRoute: typeof CheckoutPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notification-lab': {
      id: '/admin/notification-lab'
      path: '/notification-lab'
      fullPath: '/admin/notification-lab'
      preLoaderRoute: typeof AdminNotificationLabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workforce': {
      id: '/admin/workforce'
      path: '/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/history': {
      id: '/kitchen/history'
      path: '/history'
      fullPath: '/kitchen/history'
      preLoaderRoute: typeof KitchenHistoryRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/menu': {
      id: '/kitchen/menu'
      path: '/menu'
      fullPath: '/kitchen/menu'
      preLoaderRoute: typeof KitchenMenuRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/notifications': {
      id: '/kitchen/notifications'
      path: '/notifications'
      fullPath: '/kitchen/notifications'
      preLoaderRoute: typeof KitchenNotificationsRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/customers': {
      id: '/admin/analytics/customers'
      path: '/customers'
      fullPath: '/admin/analytics/customers'
      preLoaderRoute: typeof AdminAnalyticsCustomersRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/inventory': {
      id: '/admin/analytics/inventory'
      path: '/inventory'
      fullPath: '/admin/analytics/inventory'
      preLoaderRoute: typeof AdminAnalyticsInventoryRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/orders': {
      id: '/admin/analytics/orders'
      path: '/orders'
      fullPath: '/admin/analytics/orders'
      preLoaderRoute: typeof AdminAnalyticsOrdersRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/revenue': {
      id: '/admin/analytics/revenue'
      path: '/revenue'
      fullPath: '/admin/analytics/revenue'
      preLoaderRoute: typeof AdminAnalyticsRevenueRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/sales': {
      id: '/admin/analytics/sales'
      path: '/sales'
      fullPath: '/admin/analytics/sales'
      preLoaderRoute: typeof AdminAnalyticsSalesRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/staff': {
      id: '/admin/analytics/staff'
      path: '/staff'
      fullPath: '/admin/analytics/staff'
      preLoaderRoute: typeof AdminAnalyticsStaffRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/monitoring/': {
      id: '/admin/monitoring/'
      path: '/'
      fullPath: '/admin/monitoring/'
      preLoaderRoute: typeof AdminMonitoringIndexRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/activity': {
      id: '/admin/monitoring/activity'
      path: '/activity'
      fullPath: '/admin/monitoring/activity'
      preLoaderRoute: typeof AdminMonitoringActivityRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/api': {
      id: '/admin/monitoring/api'
      path: '/api'
      fullPath: '/admin/monitoring/api'
      preLoaderRoute: typeof AdminMonitoringApiRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/database': {
      id: '/admin/monitoring/database'
      path: '/database'
      fullPath: '/admin/monitoring/database'
      preLoaderRoute: typeof AdminMonitoringDatabaseRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/errors': {
      id: '/admin/monitoring/errors'
      path: '/errors'
      fullPath: '/admin/monitoring/errors'
      preLoaderRoute: typeof AdminMonitoringErrorsRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/integrations': {
      id: '/admin/monitoring/integrations'
      path: '/integrations'
      fullPath: '/admin/monitoring/integrations'
      preLoaderRoute: typeof AdminMonitoringIntegrationsRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/live': {
      id: '/admin/monitoring/live'
      path: '/live'
      fullPath: '/admin/monitoring/live'
      preLoaderRoute: typeof AdminMonitoringLiveRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/monitoring/performance': {
      id: '/admin/monitoring/performance'
      path: '/performance'
      fullPath: '/admin/monitoring/performance'
      preLoaderRoute: typeof AdminMonitoringPerformanceRouteImport
      parentRoute: typeof AdminMonitoringRoute
    }
    '/admin/organization/': {
      id: '/admin/organization/'
      path: '/'
      fullPath: '/admin/organization/'
      preLoaderRoute: typeof AdminOrganizationIndexRouteImport
      parentRoute: typeof AdminOrganizationRoute
    }
    '/admin/organization/analytics': {
      id: '/admin/organization/analytics'
      path: '/analytics'
      fullPath: '/admin/organization/analytics'
      preLoaderRoute: typeof AdminOrganizationAnalyticsRouteImport
      parentRoute: typeof AdminOrganizationRoute
    }
    '/admin/organization/campuses': {
      id: '/admin/organization/campuses'
      path: '/campuses'
      fullPath: '/admin/organization/campuses'
      preLoaderRoute: typeof AdminOrganizationCampusesRouteImport
      parentRoute: typeof AdminOrganizationRoute
    }
    '/admin/organization/canteens': {
      id: '/admin/organization/canteens'
      path: '/canteens'
      fullPath: '/admin/organization/canteens'
      preLoaderRoute: typeof AdminOrganizationCanteensRouteImport
      parentRoute: typeof AdminOrganizationRoute
    }
    '/admin/organization/settings': {
      id: '/admin/organization/settings'
      path: '/settings'
      fullPath: '/admin/organization/settings'
      preLoaderRoute: typeof AdminOrganizationSettingsRouteImport
      parentRoute: typeof AdminOrganizationRoute
    }
    '/admin/workforce/': {
      id: '/admin/workforce/'
      path: '/'
      fullPath: '/admin/workforce/'
      preLoaderRoute: typeof AdminWorkforceIndexRouteImport
      parentRoute: typeof AdminWorkforceRoute
    }
    '/admin/workforce/attendance': {
      id: '/admin/workforce/attendance'
      path: '/attendance'
      fullPath: '/admin/workforce/attendance'
      preLoaderRoute: typeof AdminWorkforceAttendanceRouteImport
      parentRoute: typeof AdminWorkforceRoute
    }
    '/admin/workforce/shifts': {
      id: '/admin/workforce/shifts'
      path: '/shifts'
      fullPath: '/admin/workforce/shifts'
      preLoaderRoute: typeof AdminWorkforceShiftsRouteImport
      parentRoute: typeof AdminWorkforceRoute
    }
    '/app/menu/': {
      id: '/app/menu/'
      path: '/menu'
      fullPath: '/app/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu/$itemId': {
      id: '/app/menu/$itemId'
      path: '/menu/$itemId'
      fullPath: '/app/menu/$itemId'
      preLoaderRoute: typeof AppMenuItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$orderId': {
      id: '/app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/app/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminAnalyticsRouteChildren {
  AdminAnalyticsCustomersRoute: typeof AdminAnalyticsCustomersRoute
  AdminAnalyticsInventoryRoute: typeof AdminAnalyticsInventoryRoute
  AdminAnalyticsOrdersRoute: typeof AdminAnalyticsOrdersRoute
  AdminAnalyticsRevenueRoute: typeof AdminAnalyticsRevenueRoute
  AdminAnalyticsSalesRoute: typeof AdminAnalyticsSalesRoute
  AdminAnalyticsStaffRoute: typeof AdminAnalyticsStaffRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
}

const AdminAnalyticsRouteChildren: AdminAnalyticsRouteChildren = {
  AdminAnalyticsCustomersRoute: AdminAnalyticsCustomersRoute,
  AdminAnalyticsInventoryRoute: AdminAnalyticsInventoryRoute,
  AdminAnalyticsOrdersRoute: AdminAnalyticsOrdersRoute,
  AdminAnalyticsRevenueRoute: AdminAnalyticsRevenueRoute,
  AdminAnalyticsSalesRoute: AdminAnalyticsSalesRoute,
  AdminAnalyticsStaffRoute: AdminAnalyticsStaffRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
}

const AdminAnalyticsRouteWithChildren = AdminAnalyticsRoute._addFileChildren(
  AdminAnalyticsRouteChildren,
)

interface AdminMonitoringRouteChildren {
  AdminMonitoringActivityRoute: typeof AdminMonitoringActivityRoute
  AdminMonitoringApiRoute: typeof AdminMonitoringApiRoute
  AdminMonitoringDatabaseRoute: typeof AdminMonitoringDatabaseRoute
  AdminMonitoringErrorsRoute: typeof AdminMonitoringErrorsRoute
  AdminMonitoringIntegrationsRoute: typeof AdminMonitoringIntegrationsRoute
  AdminMonitoringLiveRoute: typeof AdminMonitoringLiveRoute
  AdminMonitoringPerformanceRoute: typeof AdminMonitoringPerformanceRoute
  AdminMonitoringIndexRoute: typeof AdminMonitoringIndexRoute
}

const AdminMonitoringRouteChildren: AdminMonitoringRouteChildren = {
  AdminMonitoringActivityRoute: AdminMonitoringActivityRoute,
  AdminMonitoringApiRoute: AdminMonitoringApiRoute,
  AdminMonitoringDatabaseRoute: AdminMonitoringDatabaseRoute,
  AdminMonitoringErrorsRoute: AdminMonitoringErrorsRoute,
  AdminMonitoringIntegrationsRoute: AdminMonitoringIntegrationsRoute,
  AdminMonitoringLiveRoute: AdminMonitoringLiveRoute,
  AdminMonitoringPerformanceRoute: AdminMonitoringPerformanceRoute,
  AdminMonitoringIndexRoute: AdminMonitoringIndexRoute,
}

const AdminMonitoringRouteWithChildren = AdminMonitoringRoute._addFileChildren(
  AdminMonitoringRouteChildren,
)

interface AdminOrganizationRouteChildren {
  AdminOrganizationAnalyticsRoute: typeof AdminOrganizationAnalyticsRoute
  AdminOrganizationCampusesRoute: typeof AdminOrganizationCampusesRoute
  AdminOrganizationCanteensRoute: typeof AdminOrganizationCanteensRoute
  AdminOrganizationSettingsRoute: typeof AdminOrganizationSettingsRoute
  AdminOrganizationIndexRoute: typeof AdminOrganizationIndexRoute
}

const AdminOrganizationRouteChildren: AdminOrganizationRouteChildren = {
  AdminOrganizationAnalyticsRoute: AdminOrganizationAnalyticsRoute,
  AdminOrganizationCampusesRoute: AdminOrganizationCampusesRoute,
  AdminOrganizationCanteensRoute: AdminOrganizationCanteensRoute,
  AdminOrganizationSettingsRoute: AdminOrganizationSettingsRoute,
  AdminOrganizationIndexRoute: AdminOrganizationIndexRoute,
}

const AdminOrganizationRouteWithChildren =
  AdminOrganizationRoute._addFileChildren(AdminOrganizationRouteChildren)

interface AdminWorkforceRouteChildren {
  AdminWorkforceAttendanceRoute: typeof AdminWorkforceAttendanceRoute
  AdminWorkforceShiftsRoute: typeof AdminWorkforceShiftsRoute
  AdminWorkforceIndexRoute: typeof AdminWorkforceIndexRoute
}

const AdminWorkforceRouteChildren: AdminWorkforceRouteChildren = {
  AdminWorkforceAttendanceRoute: AdminWorkforceAttendanceRoute,
  AdminWorkforceShiftsRoute: AdminWorkforceShiftsRoute,
  AdminWorkforceIndexRoute: AdminWorkforceIndexRoute,
}

const AdminWorkforceRouteWithChildren = AdminWorkforceRoute._addFileChildren(
  AdminWorkforceRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRouteWithChildren
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminMonitoringRoute: typeof AdminMonitoringRouteWithChildren
  AdminNotificationLabRoute: typeof AdminNotificationLabRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrganizationRoute: typeof AdminOrganizationRouteWithChildren
  AdminQaRoute: typeof AdminQaRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkforceRoute: typeof AdminWorkforceRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRouteWithChildren,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminMonitoringRoute: AdminMonitoringRouteWithChildren,
  AdminNotificationLabRoute: AdminNotificationLabRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrganizationRoute: AdminOrganizationRouteWithChildren,
  AdminQaRoute: AdminQaRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkforceRoute: AdminWorkforceRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMenuItemIdRoute: typeof AppMenuItemIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppMenuItemIdRoute: AppMenuItemIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface KitchenRouteChildren {
  KitchenHistoryRoute: typeof KitchenHistoryRoute
  KitchenMenuRoute: typeof KitchenMenuRoute
  KitchenNotificationsRoute: typeof KitchenNotificationsRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
}

const KitchenRouteChildren: KitchenRouteChildren = {
  KitchenHistoryRoute: KitchenHistoryRoute,
  KitchenMenuRoute: KitchenMenuRoute,
  KitchenNotificationsRoute: KitchenNotificationsRoute,
  KitchenIndexRoute: KitchenIndexRoute,
}

const KitchenRouteWithChildren =
  KitchenRoute._addFileChildren(KitchenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CheckoutPlanRoute: CheckoutPlanRoute,
  ContactRoute: ContactRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenRoute: KitchenRouteWithChildren,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfflineRoute: OfflineRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServerErrorRoute: ServerErrorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
